// Copyright (c) 2026 ACR Engineering Group. All rights reserved.
// Licensed under the Apache License, Version 2.0.

import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');
  final entryHeader = packageRoot.resolve(
    'third_party/acr_crypto/acr_crypto.h',
  );
  final bindingsOutput = packageRoot.resolve(
    'lib/src/third_party/acr_crypto.g.dart',
  );
  final treeShakeMapping = packageRoot.resolve(
    'lib/src/third_party/acr_crypto.record_use_mapping.g.dart',
  );

  FfiGenerator(
    headers: Headers(entryPoints: [entryHeader]),
    functions: Functions(
      include: (decl) => {
        'acr_verify_state_hash',
        'acr_verify_ast_diff_invariants',
        'acr_evaluate_rate_limit',
      }.contains(decl.originalName),
      recordUse: (_) => true,
    ),
    output: Output(
      dartFile: bindingsOutput,
      recordUseMapping: treeShakeMapping,
      format: true,
      preamble: '''
// Copyright (c) 2026 ACR Engineering Group. All rights reserved.
// Licensed under the Apache License, Version 2.0.
// Generated by package:ffigen. Do not edit manually.

// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package, experimental_member_use
''',
    ),
  ).generate();

  print('Successfully generated ACR Crypto FFI bindings.');
}
